#!/usr/bin/python
# -*- coding: latin-1 -*-

import csv
import json

f = open( 'porCurso.csv', 'r' )

reader = csv.DictReader( f, fieldnames = ( "CURSOS","ADMINISTRACAO/DIURNO","ADMINISTRACAO/NOTURNO","CIENCIAS CONTABEIS/NOTURNO","CIENCIAS ECONOMICAS","DIREITO/DIURNO","DIREITO/NOTURNO","BIBLIOTECONOMIA/DIURNO","BIBLIOTECONOMIA/NOTURNO","CIENCIAS SOCIAIS","COMUNICACAO SOCIAL/DIURNO","FILOSOFIA","HISTORIA/DIURNO","HISTORIA/NOTURNO","PSICOLOGIA","LETRAS/DIURNO","LETRAS/NOTURNO","PEDAGOGIA/DIURNO","PEDAGOGIA/NOTURNO","ARTES VISUAIS","TEATRO","MUSICA/DIURNO","GEOGRAFIA/DIURNO","GEOGRAFIA/NOTURNO","GEOLOGIA","TURISMO","ARQUITETURA E URBANISMO/DIURNO","CIENCIA DA COMPUTACAO","SISTEMAS DE INFORMACAO","CIENCIAS ATUARIAIS","ESTATISTICA","FISICA/DIURNO","FISICA/NOTURNO","MATEMATICA/DIURNO","MATEMATICA/NOTURNO","MATEMATICA COMPUTACIONAL","QUIMICA/DIURNO","QUIMICA/NOTURNO","ENGENHARIA CIVIL","ENG. CONTROLE AUTOMACAO/DIURNO","ENGENHARIA DE MINAS","ENGENHARIA DE PRODUCAO","ENGENHARIA ELETRICA","ENGENHARIA MECANICA-DIURNO","ENGENHARIA MECANICA-NOTURNO","ENGENHARIA METALURGICA","ENGENHARIA QUIMICA","FARMACIA-Diurno","MEDICINA VETERINARIA","EDUCACAO FISICA","FISIOTERAPIA","TERAPIA OCUPACIONAL","ENFERMAGEM","NUTRICAO","MEDICINA","FONOAUDIOLOGIA","ODONTOLOGIA","CIENCIAS BIOLOGICAS/DIURNO","CIENCIAS BIOLOGICAS/NOTURNO","AGRONOMIA","ZOOTECNIA") )
out = json.dumps( [ row for row in reader ] )
output = json.loads(out)

cursos = []

for i in output:
	j = {}
	#print i
	j['name'] = str(i['CURSOS'])
	del i['CURSOS']
	#print i
	
	childs = []
	for key in i.keys():
		size = "%.4f" % float(str(i[key]).replace(',','.'))
		size = int(float(size)*1000)
		children = {}
		children['name']=key.encode('utf-8')
		children['size']=size
		if (size>10):
			childs.append(children)
		#print childs
		
	#children['name'] = i[
	j['children'] = childs
	cursos.append(j)

print cursos